language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    - secure: JUn9VwOySvLCA2nT0T8ZV3o9zok0Mw7pTrmx+JWzfzL9hKei9kyviY+IvDgH3tVj2KG7fB90VDjtfgcLlQkDEolGrrNQbeM64kMfrFnu95kPmsSo/XGn3T0ADqH0JlJ/YQcTcC7eP9ebJFY9czceABpnJh2MOTO0IHcGqMf4655UNcq6tnmtnFI4S70pRge1QVZCeucMAUSU/hycJXJRDz4E88iOGzr3hVkJzW9bW6fT7I5D6U4VcuZIq9SQoMilJ792L1JR7nmPwztePZARltjXio9k7Ycg99u8cDIh7DgmtzWXLPrxKzATX7tF3BgB6rTux9cSJY9J3MHFnJ04vCSnP2QJ3niGQbfB1xShE+5PMjHrJBFltTECDM9qFW7HwVOl84mtOLPGeqEh0XlJ2JiZbSFgyWx8+nQqSK1mXu6dyXi3JrBhpKUvkpePPwthYbFjAR9auWyd/ire1k6mlJQvxE0tw6HQ++s69anVD/GzCZu6lpu3ZqBGcEKRuwyLohwW8VXjX+8yAjudcktq4ZuKV+pXzEj0g1oVSv13UBu8wfTuD1gVc/0aXLx8tAzP2ss07N61/J7hLrJAbKpXeyCVQjVPcNtjUq/DM7j+s9MwKUZmZqmHzZfZAz9bPSFpD6gRlWciqSBPoEGRSDQbvpOdn32GeyiSDAR0yo4QrGg=
env:
  global:
    - secure: WbgbfTJEBIc/rxxPh0E2epIc2wOVEOmtedXDdzposYgkVMEQUkPt0uk7jYj+MWKlJzcrdOeX2wVPAb+3iMAUdxF/VN5zR9eJqRTNKieX6oHSIdcHOKFJwTSLnF+6Y2yy2A6oXV9jRvCP4tiKCwoJvUZzAF501coYHRenr2UNFEd9uxGWnRHuk+PmPtHi9iqbKXfYizApJB8mTtKZSesvWJdBx5POz00G1iT8sKY+fUNTKFviXQOQ1docoeylY9bzDXGwqXmCkuVtSPCPqTW/uSe9LuHlQe6JUJPFiqYeXAMdW6mRwLHOcYOrZ8eDVevVmvriMX4as6akcinBZWuSR7DjuyadZOLChc5kiCHSmgnGPUBqGCJlmq+KCIRIKwAYRxSqiifVy81HHVQHfnIZaj8lBjZ356jwxne4I7nHLR9YaxCPjfrkpq2WJZiM3wjuVX3fNF00SCmWa9A2iYR8pPzc5EfFREzCG7cWtdK2/aGTN1X1at16H0GzzGmqsVlcuuYcXigxhtt3LWE1P6VsnnRBWIuOvMH979ijq6OwJO4faUp6SfNIIGq1FDKF4EPriWStjj70MQT+edxoVpzDBMbDZQeo1fV0pvtGF9d2J6qDfy0eYjTLBvYp5ylcgNvWPUEQjpJIsHLHsw7rIxfP43X6IPsVdfexVAAYGWLHhLw=
    - secure: KBYrVUsMDhFDTI9fA8ebFlWM2X0EbZv2lGTDBitvFp2o9X4ONkmUap6oicUvIvxSbUT8MSZ1c8lm0Z48teeo2Z5y02407xEvRE2cE/wZ+/Q9O9iSY0euh+16xEWE3o5FT8EUDe8+UcYhuIsN69rYO1DWXRAuzLiMRu1LrFtudPWrjquoZQe1sIboyXWVAjurSXqAAUrF9i2NDATFsyd28dNsfBJ98mMIa2LHCHOqquXmRtTgBan51ui50Dw6j0siAVCKcpNl0mSSE+ShYrYvn4X38PTikR4ZCUJpDcj1LjEntkvKkgUF+I/bFyOdfvR1Zim3RO8MM0gyRMlxLUd8Da6vh82tzFnwFj6ml/z7KAdHCsMfUa+ekSNLf1tQvQNtop3nxllU1A64kjbb4fitEWLuMGRObM6Kct1SMB3d5yVHBm5/7CcLw4j4piNVE/8yAvvhgnhob8lCaA2a2kzyibBlvIXkigrLjaxfp/nUBGYzxqCQMPeP/lU8NAIdcrdVsDgec4yw/uuAQV/TavEVJ01aKSRsAb/1tp81DnFlGLHvtkKek78tfG4MbMHW/i9lYmGloCeP5CJyAQuE6h3NNfVApBKOdl+O2ZTCO47PTeS/cJTVFy+F6TOfQk+ja/s9S5ikz71W7M91Fch5yitBDSWPtdh0TnamuLNN1aKT/xI=
